### ISSUE TITLE
version 1.6 do not recognize Avaritia 1.10.2-2.1.2.1

### ISSUE THREAD

**Issue by myaofcars** [abused/Avaritia-Additions#16]
As title,when launching with Addition 1.6 and avaritia 2.1.2.1,it says Addition is missing mods it depends on,showing "Avaritia :any"
By downgrading Addition to version 1.5,Addition recognize and game run smoothly.I dont know why but it feels like version 1.6 does not want to recognize newer version of Avaritia

**Comment by MSandro** [comment]
I also heave this problem, please fix!

**Comment by CamaroKing69** [comment]
is this Ever going to get fixed???

**Comment by alothmanmoe** [comment]
I refer to https://github.com/abused/Avaritia-Additions/issues/18
