### ISSUE TITLE
avarita additions missing avaritia:any

### ISSUE THREAD

**Issue by lawfulrocky** [abused/Avaritia-Additions#18]
i keep saying avaritia is missing wheni have it in my modpack and i dont know why it is doing that

**Comment by DeadSix27** [comment]
@abused Any solution to this?

**Comment by alothmanmoe** [comment]
Try an older version of Avaritia Additions, though i don't know why'd you need the mod anymore Avaritia pretty much has everything added in now so its useless, *shrugs*, anyways this mod is discontinued because Avaritia has added everything now

**Comment by DeadSix27** [comment]
@abused Oh haha, sorry I did not play for a while and just remembered that the original mod did not have all the stuff yet.. but now that it does.. I guess you are correct.

**Comment by alothmanmoe** [comment]
Yeah no worries, just glad that's cleared up
