### ISSUE TITLE
Bow Doesnt Do Anything But Make Noise

### ISSUE THREAD

**Issue by Boolyman** [abused/Avaritia-Additions#2]
When using the new Avaritia Bow with or without arrows in my inventory, nothing happens except the sound of arrows landing.  No arrows are fired, no mobs are damaged, just the sound effect of about a dozen arrows landing on dirt... but no actual arrows.

Minecraft 1.10
Avaritia 1.4

**Comment by alothmanmoe** [comment]
Fixed in v1.5
