### ISSUE TITLE
Infinity armor's texture layers break when flying

### ISSUE THREAD

**Issue by Froggy800** [abused/Avaritia-Additions#5]
As per title; the armor's layers get messed up when flight is active, even getting smaller than the outer texture layer of the player's skin.
Screenshots to show the comparison:
![2017-04-07_17 41 53](https://cloud.githubusercontent.com/assets/25703114/24807709/9599f086-1bb9-11e7-9f74-83e20eea7906.png)
![2017-04-07_17 41 54](https://cloud.githubusercontent.com/assets/25703114/24807710/95aeb5e8-1bb9-11e7-8ce9-bf4548178a4a.png)

**Comment by alothmanmoe** [comment]
Please keep it to 1 issue instead of making multiple put them in 1, sadly the armor is broken when flying due to the render system in 1.10.2 and porting code straight from 1.7.10, nothing much i can do about it unless a rewrite and overhaul, the layers getting smaller is a feature not a bug,

**Comment by Froggy800** [comment]
Sorry about the double issues, I separated them because one was about missing features, the other about a bug.
I guess the problem with the armor shrinking is that it is not possible anymore to change an armor's model, so you "fixed" it by making only one layer visible at a time? I know for sure Modular power suit for 1.10 has some workaround for it that allows an switching of the model, maybe you could ask the developers.
By the way this is the main problem: if you have outer layers on your skin they get rendered above the armor
![2017-04-07_18 07 16](https://cloud.githubusercontent.com/assets/25703114/24808724/40a696ca-1bbd-11e7-90f3-153980dafe13.png)
