### ISSUE TITLE
Remove Recipe command Not Working.

### ISSUE THREAD

**Issue by Boolyman** [abused/Avaritia-Additions#6]
I want to make the singularities all cost the same amount of materials, Instead of a Lapis Singularity costing 400 Lapis Blocks, but a gold singularity only costs 200 blocks.  I attempted to remove the old recipes and add the new ones via the minetweaker syntax you listed on the curse page...

mods.avaritiaadditions.Compressor.remove(<avaritiaadditions:lapis_singularity>);
mods.avaritiaadditions.Compressor.add(<avaritiaadditions:lapis_singularity>, 200, <minecraft:lapis_block>)

Unfortunately it doesn't seem like the compressor is responding to the remove recipe command... and therefore won't accept the new recipes I am trying to add.  Is this intended?  Are we not allowed to change the current recipes for the compressor?

**Comment by alothmanmoe** [comment]
The recipes cannot be removed only new ones added, instead open the config and you can edit the amount they all need in it

**Comment by Boolyman** [comment]
Oh wow, I cant believe I missed that in the configs.  Sorry for the useless ticket.
