### ISSUE TITLE
Abnormal despawning timers on dropped items

### ISSUE THREAD

**Issue by Froggy800** [abused/Avaritia-Additions#8]
The World Breaker, Planet Eater, Nature's Ruin and Sword of the Cosmos despawn almost instantly after being dropped in the world, to the point that it's not possible to pick them up again or even toss them to another player. Also, every single dropped item in both avaritia and avaritia additions disappear only after one minute, instead of the usual five.

**Comment by alothmanmoe** [comment]
That doesn't sound like a problem on my end, there is nothing that i did for despawning it should be normal vanilla mechanics

**Comment by Froggy800** [comment]
Well, the items taking one minute to despawn aren't really a problem, but the tools disappearing after attempting to give them to another player are kind of a big deal. Anyway, since you said that this is not an error on your part, should I report the issue to brandon3055, Avaritia's dev?

**Comment by alothmanmoe** [comment]
No, this isn't an issue on his end either, im looking into it atm and i will reply if i find something

**Comment by alothmanmoe** [comment]
Ok so i seem to have found the problem, while linking my custom entity to the tools it seems the entity class was causing it, it should be an easy fix, ill push an update soon

**Comment by alothmanmoe** [comment]
releasing a new version in about an hour
